[platformio]
default_envs = esp8266_slave

[env:esp8266_slave]
platform = espressif8266
board = esp12e
framework = arduino
upload_port = COM5
monitor_port = COM5
monitor_speed = 115200
lib_deps = fastled/FastLED@^3.6.0
build_flags =
    -I../common
    -D ITEMLIB_BOX_ID=1
    -D ITEMLIB_ESPNOW_CHANNEL=1
    -D ITEMLIB_LED_DATA_PIN=4
    -D ITEMLIB_BOX_LED_PIN=5
    -D ITEMLIB_LED_COUNT=81
    -D ITEMLIB_BOX_LED_COUNT=12
    -D ITEMLIB_LED_BRIGHTNESS=96
